gpu_selection: A100-40GB|A100-80GB|H100|H200|V100-16GB|V100-32GB|RTX6000|A40|L40S
llm_bash_script: '#!/bin/bash

    #SBATCH --job-name=llm_oper

    #SBATCH -t 8:00:00

    #SBATCH --mem-per-gpu 16G

    #SBATCH -G 1

    #SBATCH -C {}

    #SBATCH -c 2

    #SBATCH -N 1

    echo "Launching AIsurBL"

    hostname


    module load cuda

    export CUDA_VISIBLE_DEVICES=0


    # Run Python script

    {}

    '
python_bash_script: '#!/bin/bash

    #SBATCH --job-name=evaluateGene

    #SBATCH -t 4:00:00

    #SBATCH --gres=gpu:1

    #SBATCH -G 1

    #SBATCH --mem 16G

    #SBATCH -c 12

    #SBATCH -N 1

    echo "Launching Python Evaluation"

    hostname


    module load cuda

    module load uv

    export CUDA_VISIBLE_DEVICES=0


    # Run Python script

    {}

    '
